var PDFtoText = require('./Watson/PDFtoText')
var languageTranslator = require('./Watson/Translation')
var TexttoSpeech = require('./Watson/TextToSpeech')
var OCR = require('./OCR/tessaractOCR')
var extractor = require('./Utilities/ExtractDataFromText.js')
